### ISSUE TITLE
Error while testing pipeline

### ISSUE THREAD

**Issue by RenscoHogers** [tuannguyen8390/nf-EXPLOR#1]
Dear Tuan,

I have been trying to use your pipeline for structural variant calling, but I have been thwarted by some issues when running the test commands.
When running "nextflow run setup.nf -profile singularity" I get an error because the meta data is not found in the location that it is expecting (it expects it to be found in "$baseDir/meta/test/backup/test_metadata_SR.csv", while it is actually found in "$baseDir/meta/test/test_metadata_SR.csv"). This issue I fixed by revising the setup.nf, which I can add as a pull request if you want me to.

However, the next step is the downloading of the sample genome and assets, however, this results in a forbidden error:
```
ERROR ~ Error executing process > 'download_asset'

Caused by:
  Process `download_asset` terminated with an error exit status (8)

Command executed:

  wget https://bovlrctest.s3.amazonaws.com/asset.zip
  unzip asset.zip

Command exit status:
  8

Command output:
  (empty)

Command error:
  --2023-08-11 15:11:16--  https://bovlrctest.s3.amazonaws.com/asset.zip
  Resolving bovlrctest.s3.amazonaws.com (bovlrctest.s3.amazonaws.com)... 3.5.10.154, 52.217.135.17, 52.217.164.65, ...
  Connecting to bovlrctest.s3.amazonaws.com (bovlrctest.s3.amazonaws.com)|3.5.10.154|:443... connected.
  HTTP request sent, awaiting response... 403 Forbidden
  2023-08-11 15:11:17 ERROR 403: Forbidden.
```

I think the data that is stored on the AWS server can only be accessed from your IP address or with your credentials, would it be possible to open this up to other people, or add it to the GitHub so the test can be completed?

**Comment by tuannguyen8390** [comment]
Hi there,


Thanks for letting me know & testing the setup.nf route. It would be very nice if you can do a quick PR for the sample tsv issue :)

The asset is a bit heavy that's why I could not include that with GitHub itself so AWS is the current solution! As bovlrctest S3 bucket contains a lot of other things (sequencing data for example) so I guess there was a conflict in the way I set up the S3 policy OR the allocated resource ran out for this month !  I will have a look at that and get back to you. 

Best,

Tuan

**Comment by RenscoHogers** [comment]
Hi Tuan,

Thanks for getting back to me, I appreciate your effort to maintain this pipeline!

As requested I have opened a pull request, if there are any issues with it, please let me know.

Cheers,
Rensco

**Comment by tuannguyen8390** [comment]
Hey Rensco,

I've just addressed the AWS bucket policy. There was a conflict in the way I set it up hence it simply denies all external connection! I just test it on my local cluster and it seems to work but it would be nice if you can test it again.

In addition, I've made a few updates - one of the major ones is to update sniffles into the newest version v2.2 & clair3 to its official version v.1.0.4

Let me know if you still run into any trouble :)

Tuan

**Comment by RenscoHogers** [comment]
Hi Tuan,

I tested the version and it seems to be working perfectly! I was able to download the test set from AWS, and being able to use the latest version of sniffles and clair3 is great.
Thank you for your effort and I am looking forward to using it on my own dataset soon :)

Kind regards,
Rensco
